"""Added year_founded to Company

Revision ID: 0c3a66a9cb40
Revises: 
Create Date: 2021-05-18 19:12:39.730520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3a66a9cb40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('year_founded', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'year_founded')
    # ### end Alembic commands ###
