"""Index for Employee.job

Revision ID: d08438d70550
Revises: 815ca6c0f551
Create Date: 2021-05-18 20:08:45.783713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08438d70550'
down_revision = '815ca6c0f551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_job'), 'employees', ['job'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_job'), table_name='employees')
    # ### end Alembic commands ###
