"""Changed year_founded type

Revision ID: f3d8ef23de06
Revises: 0c3a66a9cb40
Create Date: 2021-05-18 19:27:58.613357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d8ef23de06'
down_revision = '0c3a66a9cb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'year_founded',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using='year_founded::integer',
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'year_founded',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True,
                    )
    # ### end Alembic commands ###
