"""added email to user

Revision ID: 05544cb41753
Revises: 6adb15d1f5e6
Create Date: 2021-05-16 23:41:12.220543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05544cb41753'
down_revision = '6adb15d1f5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_news_url'), ['url'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_news_url'), type_='unique')

    # ### end Alembic commands ###
