"""added email to user

Revision ID: 774392304432
Revises: 6adb15d1f5e6
Create Date: 2021-04-05 16:59:41.338813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774392304432'
down_revision = '6adb15d1f5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
